### ISSUE TITLE
How to use getTasks in lists.js

### ISSUE THREAD

**Issue by jonathandavis805** [ComfortablyCoding/clickup.js#21]
Could you provide some examples of how to use the options param in getTasks in the lists.js file. Clickup's own documentation provides pretty basic examples and the accepted parameters but I can't find anyone who's used the filter by status using an array of statuses as a url param. Let me know if I can provide more detail, but I'm at a loss as to how to format this request.

**Comment by ComfortablyCoding** [comment]
From the Clickup API docs an example of making such a request using this lib:

```js
const clickup = new Clickup("some token");
const listId = 123;
const params = {
	"statuses[]": ["in progress"],
};

try {
	const { body } = await clickup.lists.getTasks(listId, params);
	console.log(body.tasks);
} catch (error) {
	console.error(error);
}
```

With only one status it returns the filtered tasks correctly, with more than one at the moment it does not seem to work. I have a potential fix that I plan to implement once I have the chance to test it properly.

I had no luck with attempting to apply this filter at all with Insome (HTTP Client) and the Clickup Console in the docs. Both of them returned unfiltered tasks. 

From what I can tell  the difference between the lib and the other two is how the query string is built. 

Hitting the endpoint from the lib generates the following URL:
```https://api.clickup.com/api/v2/list/1234/task?statuses%5B%5D=in+progress&archived=false```
While the URL generated from the other two is:
```https://api.clickup.com/api/v2/list/1234/task?archived=false&statuses%5B%5D=%5B%22in%20progress%22%5D```

At this point I am not sure if the problem is on Clickups side or from how the requests are being built. Will try to look into this further and keep you updated.

Hope this helps.

**Comment by jonathandavis805** [comment]
I talked with the team at clickup on Friday and they suggested the following. "statuses%5B%5D=status1&statuses%5B%5D=status2" which is working for me.
For each additional status you want to filter by you add an additional parameter. It doesn't seem like that's what they intended to do but it works.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
